### ISSUE TITLE
Daily limit

### ISSUE THREAD

**Issue by Paultje52** [benkaiser/youtube-playlist-info#10]
I'm making a bot with youtube playlist support. But when I use this code:
```js
        if (!queue.hasOwnProperty(message.guild.id)) queue[message.guild.id] = {}, queue[message.guild.id].playing = false, queue[message.guild.id].songs = [];
        var id = getYotubePlaylistId(args[0]);
        ytpi(ytkey, id).then(items => {
          message.channel.send(`**${items.length}** liedjes toevoegen aan de queue voor **${message.author.username}**, Geschatte tijd: ${Math.round(items.length * 1.25)} secondes!`).then(msg => {
            var plat = "YouTube";
            var count = 0;
            items.forEach(item => {
              ytsearch(`${item.title}`, opts, function(err, results) {
                if (err) return message.channel.send(`Er ging iets fout: \`\`\`${err}\`\`\``);
                console.log(results)
                return;
                var url = results[0].link
                yt.getInfo(item.resourceId.videoId, (err, info) => {
                  if (err) return message.channel.send(`Er ging iets fout: \`\`\`${err}\`\`\``);
                  queue[message.guild.id].songs.push({url: url, title: info.title, requester: message.author.username, platform: plat, id: message.author.id});
                  count++;
                  if (count === items.length) {
                    if (queue[message.guild.id].playing) return msg.edit(`**${items.length}** liedjes toegevoegd in de queue voor **${message.author.username}**`);
                    msg.edit(`**${items.length}** liedjes toegevoegd in de queue voor **${message.author.username}**. 1e afspelen...`)
                    playMusic(voiceChannel);
                  }
                })
              })
            })
          })
        }).catch(console.error);
```
I get every time the same error: 
```
Error: Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.
```
I have a working YouTubeAPI, becouse i can use it in **EVERY** other package exept this one

Edit: This is the only package that i can use, so please react

**Comment by benkaiser** [comment]
I personally solve this in my applications by having the users OAuth with
YouTube which fixes the limit.

You can add another form of authentication support if you want (maybe you
can pass a key instead). PRs welcome, I'm not actively working on this repo.

**Comment by Paultje52** [comment]
But how?

**Comment by benkaiser** [comment]
Actually my apologies, I was thinking about a different issue.

it is really odd you are hitting this as you are passing you're API key and we are authenticating internally using the [youtube-api](https://github.com/IonicaBizau/youtube-api) module.

Perhaps make sure your api key is correct? and if it is, add some more logging in the youtube-api module to see if it is authenticating correctly. You could also run a tool like wireshark or fiddler to inspect the network requests it is making ensuring the api key is being passed / received by youtube correctly.

**Comment by Paultje52** [comment]
I don't understand you and my API is working, that's the only thing I know. I don't know anything from modules.

**Comment by Paultje52** [comment]
???

**Comment by benkaiser** [comment]
See how in the node_modules folder it installed youtube-api? You want to add some debugging lines of code in there to diagnose what kind of request it is sending.

If that is to complex then maybe go look for another module.

**Comment by Paultje52** [comment]
There is no other module
