### ISSUE TITLE
TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by Tomz3n** [benkaiser/youtube-playlist-info#6]
![image](https://user-images.githubusercontent.com/6745159/33302299-07e604f6-d436-11e7-9509-772422b0ec89.png)

Using Node.JS for a discord bot, not all playlists give me this error, only a few. This random playlist for example: https://www.youtube.com/watch?v=VuNIsY6JdUw&list=PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl

**Comment by benkaiser** [comment]
Not sure, I'm not actively working on this repo, so feel free to make a PR with a fix if you can work it out

**Comment by Tomz3n** [comment]
I'm not sure either, I don't know how it could be undefined, since you can see above it passing through.

**Comment by FireController1847** [comment]
@Tomz3n Mind sharing the actual code part? I'll see if I can repro and make a pull to fix if it's an actual bug.

**Comment by Tomz3n** [comment]
file 1:
```
const youtube = require('youtube-api');
const fs = require('fs');

function playlistInfoRecursive(playlistId, callStackSize, pageToken, currentItems, callback) {
  youtube.playlistItems.list({
    part: 'snippet',
    pageToken: pageToken,
    maxResults: 50,
    playlistId: playlistId,
  }, function(err, data) {
    if (err) return callback(err);
    for (const x in data.items) {
      currentItems.push(data.items[x].snippet);
    }
    if (data.nextPageToken) {
      playlistInfoRecursive(playlistId, callStackSize + 1, data.nextPageToken, currentItems, callback);
    } else {
      callback(null, currentItems);
    }
  });
}

module.exports = function playlistInfo(apiKey, playlistId) {
  return new Promise((resolve, reject) => {
    if (!apiKey) return reject(new Error('No API Key Provided'));
    if (!playlistId) return reject(new Error('No Playlist ID Provided'));
    youtube.authenticate({
      type: 'key',
      key: apiKey
    });
    playlistInfoRecursive(playlistId, 0, null, [], (err, list) => {
      if (err) return reject(err);
      return resolve(list);
    });
  });
};
```

file 2 (snippet):
```
const playlistInfo = require('./youtube-playlist.js');

link = args[1];
ytplaylist = link.substring(link.indexOf("&list=") + 6);

if(ytplaylist.indexOf("&") > -1) {
    ytplaylist = ytplaylist.substring(0, ytplaylist.indexOf('&'));
}

console.log(`[DEBUG] Playlist ID: ${ytplaylist}`);
playlistInfo(ytapi, ytplaylist).then(items => {
    for (var i=0; i<items.length; i++) {
        link = "https://www.youtube.com/watch?v=" + items[i].resourceId.videoId;
        server.queue.push(link);
    }
}).catch(console.error);
```

**Comment by FireController1847** [comment]
Can I have the ID of the playlist you're testing?

**Comment by Tomz3n** [comment]
As I said before, the one I posted above gives me that error. A few other playlists I've come across also do it.

ID: PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl

**Comment by FireController1847** [comment]
Ah sorry, I didn't see it in the original post. Let me test it now.

**Comment by FireController1847** [comment]
The playlist returns correctly for me, let me try your example code.

**Comment by FireController1847** [comment]
Okay, so I ran this test code:

```js
const playlistInfo = require('../src/index.js');

console.log(`[DEBUG] Playlist ID: ${"PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl"}`);
playlistInfo(process.env.API_KEY, "PLMC9KNkIncKvYin_USF1qoJQnIyMAfRxl", {}).then(items => {
  for (var i=0; i<items.length; i++) {
    const link = "https://www.youtube.com/watch?v=" + items[i].resourceId.videoId;
    console.log(link);
  }
}).catch(console.error);
```

And this is working fine. It could possibly be an issue with your playlist ID getting.

⚠️ EDIT: It seems that your "URL" is saying that it's not a string. You could try doing this below to fix your issue:
```js
playlistInfo(ytapi, ytplaylist.toString()).then(items => {
```

**Comment by Tomz3n** [comment]
The problem was either with my script or [npm url](https://www.npmjs.com/package/url), but apparently using ```link = String(link)``` fixed it, honestly not sure why, it should be a string anyway. But either way it was fixed.

**Comment by FireController1847** [comment]
Awesome, glad you solved the problem. (You can close this issue now)
